// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package pb

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Err int32

const (
	Err_Success Err = 0
	Err_OOS     Err = 1
)

var Err_name = map[int32]string{
	0: "Success",
	1: "OOS",
}

var Err_value = map[string]int32{
	"Success": 0,
	"OOS":     1,
}

func (x Err) String() string {
	return proto.EnumName(Err_name, int32(x))
}

func (Err) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

type Color int32

const (
	Color_White Color = 0
	Color_Red   Color = 1
	Color_Green Color = 2
	Color_Blue  Color = 3
)

var Color_name = map[int32]string{
	0: "White",
	1: "Red",
	2: "Green",
	3: "Blue",
}

var Color_value = map[string]int32{
	"White": 0,
	"Red":   1,
	"Green": 2,
	"Blue":  3,
}

func (x Color) String() string {
	return proto.EnumName(Color_name, int32(x))
}

func (Color) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

type Student struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=Age,proto3" json:"Age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}
func (m *Student) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Student.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return m.Size()
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type Car struct {
	VarEnum              Color               `protobuf:"varint,1,opt,name=VarEnum,proto3,enum=pb.Color" json:"VarEnum,omitempty"`
	VarString            string              `protobuf:"bytes,2,opt,name=VarString,proto3" json:"VarString,omitempty"`
	VarBool              bool                `protobuf:"varint,3,opt,name=VarBool,proto3" json:"VarBool,omitempty"`
	VarByte              bool                `protobuf:"varint,4,opt,name=VarByte,proto3" json:"VarByte,omitempty"`
	VarSbyte             bool                `protobuf:"varint,5,opt,name=VarSbyte,proto3" json:"VarSbyte,omitempty"`
	VarInt16             int32               `protobuf:"varint,6,opt,name=VarInt16,proto3" json:"VarInt16,omitempty"`
	VarUint16            uint32              `protobuf:"varint,7,opt,name=VarUint16,proto3" json:"VarUint16,omitempty"`
	VarInt32             int32               `protobuf:"varint,8,opt,name=VarInt32,proto3" json:"VarInt32,omitempty"`
	VarUint32            uint32              `protobuf:"varint,9,opt,name=VarUint32,proto3" json:"VarUint32,omitempty"`
	VarInt64             int64               `protobuf:"varint,10,opt,name=VarInt64,proto3" json:"VarInt64,omitempty"`
	VarUint64            uint64              `protobuf:"varint,11,opt,name=VarUint64,proto3" json:"VarUint64,omitempty"`
	VarFloat32           float32             `protobuf:"fixed32,12,opt,name=VarFloat32,proto3" json:"VarFloat32,omitempty"`
	VarFloat64           float64             `protobuf:"fixed64,13,opt,name=VarFloat64,proto3" json:"VarFloat64,omitempty"`
	VarStruct            *Student            `protobuf:"bytes,14,opt,name=VarStruct,proto3" json:"VarStruct,omitempty"`
	VarArray             []int32             `protobuf:"varint,15,rep,packed,name=VarArray,proto3" json:"VarArray,omitempty"`
	VarStructs           []*Student          `protobuf:"bytes,16,rep,name=VarStructs,proto3" json:"VarStructs,omitempty"`
	VarBools             []bool              `protobuf:"varint,17,rep,packed,name=VarBools,proto3" json:"VarBools,omitempty"`
	VarStrings           []string            `protobuf:"bytes,18,rep,name=VarStrings,proto3" json:"VarStrings,omitempty"`
	VarFloat32S          []float32           `protobuf:"fixed32,19,rep,packed,name=VarFloat32s,proto3" json:"VarFloat32s,omitempty"`
	VarFloat64S          []float64           `protobuf:"fixed64,20,rep,packed,name=VarFloat64s,proto3" json:"VarFloat64s,omitempty"`
	VarEnums             []Color             `protobuf:"varint,21,rep,packed,name=VarEnums,proto3,enum=pb.Color" json:"VarEnums,omitempty"`
	VarMap               map[string]string   `protobuf:"bytes,22,rep,name=VarMap,proto3" json:"VarMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	VarMap1              map[string]*Student `protobuf:"bytes,23,rep,name=VarMap1,proto3" json:"VarMap1,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}
func (m *Car) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Car.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return m.Size()
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetVarEnum() Color {
	if m != nil {
		return m.VarEnum
	}
	return Color_White
}

func (m *Car) GetVarString() string {
	if m != nil {
		return m.VarString
	}
	return ""
}

func (m *Car) GetVarBool() bool {
	if m != nil {
		return m.VarBool
	}
	return false
}

func (m *Car) GetVarByte() bool {
	if m != nil {
		return m.VarByte
	}
	return false
}

func (m *Car) GetVarSbyte() bool {
	if m != nil {
		return m.VarSbyte
	}
	return false
}

func (m *Car) GetVarInt16() int32 {
	if m != nil {
		return m.VarInt16
	}
	return 0
}

func (m *Car) GetVarUint16() uint32 {
	if m != nil {
		return m.VarUint16
	}
	return 0
}

func (m *Car) GetVarInt32() int32 {
	if m != nil {
		return m.VarInt32
	}
	return 0
}

func (m *Car) GetVarUint32() uint32 {
	if m != nil {
		return m.VarUint32
	}
	return 0
}

func (m *Car) GetVarInt64() int64 {
	if m != nil {
		return m.VarInt64
	}
	return 0
}

func (m *Car) GetVarUint64() uint64 {
	if m != nil {
		return m.VarUint64
	}
	return 0
}

func (m *Car) GetVarFloat32() float32 {
	if m != nil {
		return m.VarFloat32
	}
	return 0
}

func (m *Car) GetVarFloat64() float64 {
	if m != nil {
		return m.VarFloat64
	}
	return 0
}

func (m *Car) GetVarStruct() *Student {
	if m != nil {
		return m.VarStruct
	}
	return nil
}

func (m *Car) GetVarArray() []int32 {
	if m != nil {
		return m.VarArray
	}
	return nil
}

func (m *Car) GetVarStructs() []*Student {
	if m != nil {
		return m.VarStructs
	}
	return nil
}

func (m *Car) GetVarBools() []bool {
	if m != nil {
		return m.VarBools
	}
	return nil
}

func (m *Car) GetVarStrings() []string {
	if m != nil {
		return m.VarStrings
	}
	return nil
}

func (m *Car) GetVarFloat32S() []float32 {
	if m != nil {
		return m.VarFloat32S
	}
	return nil
}

func (m *Car) GetVarFloat64S() []float64 {
	if m != nil {
		return m.VarFloat64S
	}
	return nil
}

func (m *Car) GetVarEnums() []Color {
	if m != nil {
		return m.VarEnums
	}
	return nil
}

func (m *Car) GetVarMap() map[string]string {
	if m != nil {
		return m.VarMap
	}
	return nil
}

func (m *Car) GetVarMap1() map[string]*Student {
	if m != nil {
		return m.VarMap1
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Err", Err_name, Err_value)
	proto.RegisterEnum("pb.Color", Color_name, Color_value)
	proto.RegisterType((*Student)(nil), "pb.Student")
	proto.RegisterType((*Car)(nil), "pb.Car")
	proto.RegisterMapType((map[string]*Student)(nil), "pb.Car.VarMap1Entry")
	proto.RegisterMapType((map[string]string)(nil), "pb.Car.VarMapEntry")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdf, 0x6e, 0xd3, 0x3c,
	0x14, 0x9f, 0xe3, 0x76, 0x69, 0x4e, 0xb7, 0x7d, 0xf9, 0xbc, 0x01, 0xd6, 0x40, 0x95, 0x19, 0x42,
	0x0a, 0x9b, 0x54, 0xd1, 0xb4, 0xaa, 0x80, 0x1b, 0xb4, 0x6e, 0x65, 0xea, 0xc5, 0x98, 0xe4, 0x8a,
	0x72, 0xed, 0x76, 0xd6, 0xa8, 0xe8, 0x92, 0xca, 0x71, 0x90, 0x7a, 0xcb, 0x53, 0xf0, 0x48, 0x5c,
	0xf2, 0x08, 0xa8, 0xbc, 0x08, 0x8a, 0x93, 0x34, 0xee, 0xc4, 0x5d, 0xce, 0xef, 0x9f, 0x8f, 0x7d,
	0xec, 0x00, 0x68, 0x99, 0xe8, 0xf6, 0x52, 0xc5, 0x3a, 0x26, 0xce, 0x72, 0x7a, 0xf2, 0x1e, 0xdc,
	0xb1, 0x4e, 0x6f, 0x65, 0xa4, 0xc9, 0x01, 0x38, 0xa3, 0x4b, 0x8a, 0x18, 0x0a, 0x30, 0x77, 0x46,
	0x97, 0x84, 0x40, 0xed, 0xa3, 0xb8, 0x97, 0xd4, 0x61, 0x28, 0xf0, 0xb8, 0xf9, 0x26, 0x3e, 0xe0,
	0xf3, 0x3b, 0x49, 0x31, 0x43, 0x41, 0x9d, 0x67, 0x9f, 0x27, 0xdf, 0x5d, 0xc0, 0x17, 0x42, 0x91,
	0x17, 0xe0, 0x4e, 0x84, 0x1a, 0x46, 0xe9, 0xbd, 0x89, 0x38, 0x08, 0xbd, 0xf6, 0x72, 0xda, 0xbe,
	0x88, 0x17, 0xb1, 0xe2, 0x25, 0x43, 0x9e, 0x81, 0x37, 0x11, 0x6a, 0xac, 0xd5, 0x3c, 0xba, 0x2b,
	0x72, 0x2b, 0x80, 0x50, 0x13, 0x31, 0x88, 0xe3, 0x85, 0x59, 0xa0, 0xc1, 0xcb, 0xb2, 0x64, 0x56,
	0x5a, 0xd2, 0x5a, 0xc5, 0xac, 0xb4, 0x24, 0xc7, 0xd0, 0xc8, 0x02, 0xa6, 0x19, 0x55, 0x37, 0xd4,
	0xa6, 0x2e, 0xb8, 0x51, 0xa4, 0x3b, 0x7d, 0xba, 0x6b, 0x3a, 0xde, 0xd4, 0x45, 0x27, 0x9f, 0xe6,
	0x86, 0x74, 0x19, 0x0a, 0xf6, 0x79, 0x05, 0x54, 0xce, 0x6e, 0x48, 0x1b, 0xb6, 0xb3, 0x1b, 0x5a,
	0xce, 0x6e, 0x48, 0xbd, 0x2d, 0x67, 0x37, 0xac, 0x9c, 0xfd, 0x1e, 0x05, 0x73, 0x94, 0x9b, 0xda,
	0x72, 0xf6, 0x7b, 0xb4, 0xc9, 0x50, 0x50, 0xe3, 0x15, 0x40, 0x5a, 0x00, 0x13, 0xa1, 0x3e, 0x2c,
	0x62, 0x91, 0x05, 0xef, 0x31, 0x14, 0x38, 0xdc, 0x42, 0x6c, 0xbe, 0xdf, 0xa3, 0xfb, 0x0c, 0x05,
	0x88, 0x5b, 0x08, 0x79, 0x55, 0x9e, 0x6d, 0x3a, 0xd3, 0xf4, 0x80, 0xa1, 0xa0, 0x19, 0x36, 0xb3,
	0x11, 0x14, 0xe3, 0xe5, 0x15, 0x5b, 0x34, 0x79, 0xae, 0x94, 0x58, 0xd1, 0xff, 0x18, 0x2e, 0xb6,
	0x67, 0x6a, 0x72, 0x66, 0x96, 0xc9, 0x85, 0x09, 0xf5, 0x19, 0x7e, 0x98, 0x63, 0xd1, 0x45, 0x50,
	0x36, 0xa2, 0x84, 0xfe, 0xcf, 0x70, 0x71, 0xfa, 0xa6, 0x2e, 0xfa, 0xcd, 0x47, 0x9b, 0x50, 0xc2,
	0x70, 0xe0, 0x71, 0x0b, 0x21, 0x0c, 0x9a, 0xd5, 0xee, 0x12, 0x7a, 0xc8, 0x70, 0xe0, 0x70, 0x1b,
	0xb2, 0x15, 0xfd, 0x5e, 0x42, 0x8f, 0x18, 0x0e, 0x10, 0xb7, 0x21, 0xf2, 0xd2, 0xac, 0x9f, 0x5d,
	0xad, 0x84, 0x3e, 0x62, 0x78, 0xfb, 0xd6, 0x6d, 0x28, 0x72, 0x06, 0xbb, 0x13, 0xa1, 0xae, 0xc5,
	0x92, 0x3e, 0x36, 0xfb, 0x39, 0x34, 0x22, 0xa1, 0xda, 0x39, 0x3a, 0x8c, 0xb4, 0x5a, 0xf1, 0x42,
	0x42, 0xda, 0xe6, 0xae, 0x5d, 0x8b, 0x65, 0x87, 0x3e, 0x31, 0xea, 0xa3, 0x6d, 0x75, 0x27, 0x97,
	0x97, 0xa2, 0xe3, 0xb7, 0xa6, 0xcb, 0x32, 0x26, 0x7b, 0x21, 0x5f, 0xe5, 0xca, 0xbc, 0x01, 0x8f,
	0x67, 0x9f, 0xe4, 0x08, 0xea, 0xdf, 0xc4, 0x22, 0x2d, 0x1f, 0x52, 0x5e, 0xbc, 0x73, 0xde, 0xa0,
	0xe3, 0x2b, 0xd8, 0xb3, 0x33, 0xff, 0xe1, 0x7d, 0x6e, 0x7b, 0x1f, 0x0c, 0xa2, 0x0a, 0x3a, 0x7d,
	0x0a, 0x78, 0xa8, 0x14, 0x69, 0x82, 0x3b, 0x4e, 0x67, 0x33, 0x99, 0x24, 0xfe, 0x0e, 0x71, 0x01,
	0xdf, 0xdc, 0x8c, 0x7d, 0x74, 0xfa, 0x1a, 0xea, 0xe6, 0x40, 0x88, 0x07, 0xf5, 0xcf, 0x5f, 0xe6,
	0x5a, 0xe6, 0x24, 0x97, 0xb7, 0x3e, 0xca, 0xb0, 0x2b, 0x25, 0x65, 0xe4, 0x3b, 0xa4, 0x01, 0xb5,
	0xc1, 0x22, 0x95, 0x3e, 0x1e, 0xf8, 0x3f, 0xd7, 0x2d, 0xf4, 0x6b, 0xdd, 0x42, 0xbf, 0xd7, 0x2d,
	0xf4, 0xe3, 0x4f, 0x6b, 0x67, 0xba, 0x6b, 0xfe, 0x18, 0xdd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x3b, 0x50, 0xcf, 0x9e, 0x3f, 0x04, 0x00, 0x00,
}

func (m *Student) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Student) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Student) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Age != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Age))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTest(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Car) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Car) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Car) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.VarMap1) > 0 {
		for k := range m.VarMap1 {
			v := m.VarMap1[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintTest(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintTest(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTest(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xba
		}
	}
	if len(m.VarMap) > 0 {
		for k := range m.VarMap {
			v := m.VarMap[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintTest(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintTest(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintTest(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0xb2
		}
	}
	if len(m.VarEnums) > 0 {
		dAtA3 := make([]byte, len(m.VarEnums)*10)
		var j2 int
		for _, num := range m.VarEnums {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintTest(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if len(m.VarFloat64S) > 0 {
		for iNdEx := len(m.VarFloat64S) - 1; iNdEx >= 0; iNdEx-- {
			f4 := math.Float64bits(float64(m.VarFloat64S[iNdEx]))
			i -= 8
			encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(f4))
		}
		i = encodeVarintTest(dAtA, i, uint64(len(m.VarFloat64S)*8))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if len(m.VarFloat32S) > 0 {
		for iNdEx := len(m.VarFloat32S) - 1; iNdEx >= 0; iNdEx-- {
			f5 := math.Float32bits(float32(m.VarFloat32S[iNdEx]))
			i -= 4
			encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(f5))
		}
		i = encodeVarintTest(dAtA, i, uint64(len(m.VarFloat32S)*4))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.VarStrings) > 0 {
		for iNdEx := len(m.VarStrings) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.VarStrings[iNdEx])
			copy(dAtA[i:], m.VarStrings[iNdEx])
			i = encodeVarintTest(dAtA, i, uint64(len(m.VarStrings[iNdEx])))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
	}
	if len(m.VarBools) > 0 {
		for iNdEx := len(m.VarBools) - 1; iNdEx >= 0; iNdEx-- {
			i--
			if m.VarBools[iNdEx] {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
		}
		i = encodeVarintTest(dAtA, i, uint64(len(m.VarBools)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if len(m.VarStructs) > 0 {
		for iNdEx := len(m.VarStructs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VarStructs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTest(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.VarArray) > 0 {
		dAtA7 := make([]byte, len(m.VarArray)*10)
		var j6 int
		for _, num1 := range m.VarArray {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA7[j6] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j6++
			}
			dAtA7[j6] = uint8(num)
			j6++
		}
		i -= j6
		copy(dAtA[i:], dAtA7[:j6])
		i = encodeVarintTest(dAtA, i, uint64(j6))
		i--
		dAtA[i] = 0x7a
	}
	if m.VarStruct != nil {
		{
			size, err := m.VarStruct.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x72
	}
	if m.VarFloat64 != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.VarFloat64))))
		i--
		dAtA[i] = 0x69
	}
	if m.VarFloat32 != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.VarFloat32))))
		i--
		dAtA[i] = 0x65
	}
	if m.VarUint64 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarUint64))
		i--
		dAtA[i] = 0x58
	}
	if m.VarInt64 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarInt64))
		i--
		dAtA[i] = 0x50
	}
	if m.VarUint32 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarUint32))
		i--
		dAtA[i] = 0x48
	}
	if m.VarInt32 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarInt32))
		i--
		dAtA[i] = 0x40
	}
	if m.VarUint16 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarUint16))
		i--
		dAtA[i] = 0x38
	}
	if m.VarInt16 != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarInt16))
		i--
		dAtA[i] = 0x30
	}
	if m.VarSbyte {
		i--
		if m.VarSbyte {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.VarByte {
		i--
		if m.VarByte {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.VarBool {
		i--
		if m.VarBool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.VarString) > 0 {
		i -= len(m.VarString)
		copy(dAtA[i:], m.VarString)
		i = encodeVarintTest(dAtA, i, uint64(len(m.VarString)))
		i--
		dAtA[i] = 0x12
	}
	if m.VarEnum != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.VarEnum))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTest(dAtA []byte, offset int, v uint64) int {
	offset -= sovTest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Student) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovTest(uint64(m.ID))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTest(uint64(l))
	}
	if m.Age != 0 {
		n += 1 + sovTest(uint64(m.Age))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Car) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VarEnum != 0 {
		n += 1 + sovTest(uint64(m.VarEnum))
	}
	l = len(m.VarString)
	if l > 0 {
		n += 1 + l + sovTest(uint64(l))
	}
	if m.VarBool {
		n += 2
	}
	if m.VarByte {
		n += 2
	}
	if m.VarSbyte {
		n += 2
	}
	if m.VarInt16 != 0 {
		n += 1 + sovTest(uint64(m.VarInt16))
	}
	if m.VarUint16 != 0 {
		n += 1 + sovTest(uint64(m.VarUint16))
	}
	if m.VarInt32 != 0 {
		n += 1 + sovTest(uint64(m.VarInt32))
	}
	if m.VarUint32 != 0 {
		n += 1 + sovTest(uint64(m.VarUint32))
	}
	if m.VarInt64 != 0 {
		n += 1 + sovTest(uint64(m.VarInt64))
	}
	if m.VarUint64 != 0 {
		n += 1 + sovTest(uint64(m.VarUint64))
	}
	if m.VarFloat32 != 0 {
		n += 5
	}
	if m.VarFloat64 != 0 {
		n += 9
	}
	if m.VarStruct != nil {
		l = m.VarStruct.Size()
		n += 1 + l + sovTest(uint64(l))
	}
	if len(m.VarArray) > 0 {
		l = 0
		for _, e := range m.VarArray {
			l += sovTest(uint64(e))
		}
		n += 1 + sovTest(uint64(l)) + l
	}
	if len(m.VarStructs) > 0 {
		for _, e := range m.VarStructs {
			l = e.Size()
			n += 2 + l + sovTest(uint64(l))
		}
	}
	if len(m.VarBools) > 0 {
		n += 2 + sovTest(uint64(len(m.VarBools))) + len(m.VarBools)*1
	}
	if len(m.VarStrings) > 0 {
		for _, s := range m.VarStrings {
			l = len(s)
			n += 2 + l + sovTest(uint64(l))
		}
	}
	if len(m.VarFloat32S) > 0 {
		n += 2 + sovTest(uint64(len(m.VarFloat32S)*4)) + len(m.VarFloat32S)*4
	}
	if len(m.VarFloat64S) > 0 {
		n += 2 + sovTest(uint64(len(m.VarFloat64S)*8)) + len(m.VarFloat64S)*8
	}
	if len(m.VarEnums) > 0 {
		l = 0
		for _, e := range m.VarEnums {
			l += sovTest(uint64(e))
		}
		n += 2 + sovTest(uint64(l)) + l
	}
	if len(m.VarMap) > 0 {
		for k, v := range m.VarMap {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovTest(uint64(len(k))) + 1 + len(v) + sovTest(uint64(len(v)))
			n += mapEntrySize + 2 + sovTest(uint64(mapEntrySize))
		}
	}
	if len(m.VarMap1) > 0 {
		for k, v := range m.VarMap1 {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovTest(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovTest(uint64(len(k))) + l
			n += mapEntrySize + 2 + sovTest(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovTest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTest(x uint64) (n int) {
	return sovTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Student) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Student: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Student: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Age", wireType)
			}
			m.Age = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Age |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Car) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Car: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Car: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarEnum", wireType)
			}
			m.VarEnum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarEnum |= Color(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VarString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarBool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VarBool = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarByte", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VarByte = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarSbyte", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VarSbyte = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarInt16", wireType)
			}
			m.VarInt16 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarInt16 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarUint16", wireType)
			}
			m.VarUint16 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarUint16 |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarInt32", wireType)
			}
			m.VarInt32 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarInt32 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarUint32", wireType)
			}
			m.VarUint32 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarUint32 |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarInt64", wireType)
			}
			m.VarInt64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarInt64 |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarUint64", wireType)
			}
			m.VarUint64 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VarUint64 |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarFloat32", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.VarFloat32 = float32(math.Float32frombits(v))
		case 13:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarFloat64", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.VarFloat64 = float64(math.Float64frombits(v))
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarStruct", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VarStruct == nil {
				m.VarStruct = &Student{}
			}
			if err := m.VarStruct.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.VarArray = append(m.VarArray, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.VarArray) == 0 {
					m.VarArray = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.VarArray = append(m.VarArray, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field VarArray", wireType)
			}
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarStructs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VarStructs = append(m.VarStructs, &Student{})
			if err := m.VarStructs[len(m.VarStructs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType == 0 {
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.VarBools = append(m.VarBools, bool(v != 0))
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen
				if elementCount != 0 && len(m.VarBools) == 0 {
					m.VarBools = make([]bool, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.VarBools = append(m.VarBools, bool(v != 0))
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field VarBools", wireType)
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarStrings", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VarStrings = append(m.VarStrings, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 19:
			if wireType == 5 {
				var v uint32
				if (iNdEx + 4) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
				iNdEx += 4
				v2 := float32(math.Float32frombits(v))
				m.VarFloat32S = append(m.VarFloat32S, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 4
				if elementCount != 0 && len(m.VarFloat32S) == 0 {
					m.VarFloat32S = make([]float32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					if (iNdEx + 4) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
					iNdEx += 4
					v2 := float32(math.Float32frombits(v))
					m.VarFloat32S = append(m.VarFloat32S, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field VarFloat32S", wireType)
			}
		case 20:
			if wireType == 1 {
				var v uint64
				if (iNdEx + 8) > l {
					return io.ErrUnexpectedEOF
				}
				v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
				iNdEx += 8
				v2 := float64(math.Float64frombits(v))
				m.VarFloat64S = append(m.VarFloat64S, v2)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				elementCount = packedLen / 8
				if elementCount != 0 && len(m.VarFloat64S) == 0 {
					m.VarFloat64S = make([]float64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					if (iNdEx + 8) > l {
						return io.ErrUnexpectedEOF
					}
					v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
					iNdEx += 8
					v2 := float64(math.Float64frombits(v))
					m.VarFloat64S = append(m.VarFloat64S, v2)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field VarFloat64S", wireType)
			}
		case 21:
			if wireType == 0 {
				var v Color
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= Color(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.VarEnums = append(m.VarEnums, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTest
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTest
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				if elementCount != 0 && len(m.VarEnums) == 0 {
					m.VarEnums = make([]Color, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v Color
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= Color(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.VarEnums = append(m.VarEnums, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field VarEnums", wireType)
			}
		case 22:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VarMap == nil {
				m.VarMap = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTest
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTest
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthTest
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthTest
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTest(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTest
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.VarMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VarMap1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VarMap1 == nil {
				m.VarMap1 = make(map[string]*Student)
			}
			var mapkey string
			var mapvalue *Student
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTest
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthTest
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthTest
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTest
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthTest
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthTest
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Student{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipTest(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthTest
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.VarMap1[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTest = fmt.Errorf("proto: unexpected end of group")
)
