etcd:
  <<: *baseETCD

log:
  level: -1 # 日志级别 -1:debug,0:info,1:warn,2:error,4:panic,5:fatal
  maxSize: 128 # 单个文件最大M
  isOpenConsole: true # 是否标准输出
  isOpenErrorFile: false # 是否打开单独的错误日志文件
  isOpenFile: true # 是否打开文件日志
  isAsync: false # 是否使用异步日志

gate:
  logPath: ./log/gate_${SERVER_ID}.log # 日志路径
  addr: 0.0.0.0 # 对外通信地址
  port: 9100 # 对外通信端口
  innerAddr: 127.0.0.1 # 内部通信地址
  innerPort: 9101 # 内部通信端口
  protocol: 1 # 1:tcp,2:websocket