// -------------------------------------------
// @file      : unused_tpl.go
// @author    : 蔡波
// @contact   : caibo923@gmail.com
// @time      : 2024/1/9 上午9:51
// -------------------------------------------

package main

func init() {
	_ = unUsedTpl
}

var unUsedTpl = `

// Struct

// MarshalTo is an autogenerated function, marshalling the struct to a byte slice
func (m *{{$Struct}})MarshalTo(data []byte) {
	size := m.Size()
	m.MarshalToSizedBuffer(data[:size])
	return
}


// Marshal{{$Struct}} is an autogenerated function, marshalling the struct to a byte slice
func Marshal{{$Struct}}(m *{{$Struct}}) []byte {
	return m.Marshal()
}





`
