//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package gs

import (
	gss "gogs/gss"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Car) DeepCopyInto(out *Car) {
	*out = *in
	if in.VarStruct != nil {
		in, out := &in.VarStruct, &out.VarStruct
		*out = new(Student)
		(*in).DeepCopyInto(*out)
	}
	if in.VarList != nil {
		in, out := &in.VarList, &out.VarList
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.VarStructs != nil {
		in, out := &in.VarStructs, &out.VarStructs
		*out = make([]*Student, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Student)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.VarBools != nil {
		in, out := &in.VarBools, &out.VarBools
		*out = make([]bool, len(*in))
		copy(*out, *in)
	}
	if in.VarStrings != nil {
		in, out := &in.VarStrings, &out.VarStrings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.VarFloat32s != nil {
		in, out := &in.VarFloat32s, &out.VarFloat32s
		*out = make([]float32, len(*in))
		copy(*out, *in)
	}
	if in.VarFloat64s != nil {
		in, out := &in.VarFloat64s, &out.VarFloat64s
		*out = make([]float64, len(*in))
		copy(*out, *in)
	}
	if in.VarEnums != nil {
		in, out := &in.VarEnums, &out.VarEnums
		*out = make([]Color, len(*in))
		copy(*out, *in)
	}
	if in.VarMap != nil {
		in, out := &in.VarMap, &out.VarMap
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.VarMap1 != nil {
		in, out := &in.VarMap1, &out.VarMap1
		*out = make(map[string]*Student, len(*in))
		for key, val := range *in {
			var outVal *Student
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Student)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.VarTeacher != nil {
		in, out := &in.VarTeacher, &out.VarTeacher
		*out = new(gss.Teacher)
		**out = **in
	}
	if in.VarTeachers != nil {
		in, out := &in.VarTeachers, &out.VarTeachers
		*out = make([]*gss.Teacher, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(gss.Teacher)
				**out = **in
			}
		}
	}
	if in.VarSubjects != nil {
		in, out := &in.VarSubjects, &out.VarSubjects
		*out = make([]gss.Subject, len(*in))
		copy(*out, *in)
	}
	if in.VarMap2 != nil {
		in, out := &in.VarMap2, &out.VarMap2
		*out = make(map[gss.Subject]gss.Subject, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.VarArray = in.VarArray
	out.VarStructArray = in.VarStructArray
	out.VarEnumArray = in.VarEnumArray
	out.VarStructArray1 = in.VarStructArray1
	if in.VarStructSlice != nil {
		in, out := &in.VarStructSlice, &out.VarStructSlice
		*out = make([]*Table, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Table)
				**out = **in
			}
		}
	}
	if in.VarStructMap != nil {
		in, out := &in.VarStructMap, &out.VarStructMap
		*out = make(map[string]*Table, len(*in))
		for key, val := range *in {
			var outVal *Table
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(Table)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.VarMap3 != nil {
		in, out := &in.VarMap3, &out.VarMap3
		*out = make(map[gss.Subject]*gss.Teacher, len(*in))
		for key, val := range *in {
			var outVal *gss.Teacher
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(gss.Teacher)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Car.
func (in *Car) DeepCopy() *Car {
	if in == nil {
		return nil
	}
	out := new(Car)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Student) DeepCopyInto(out *Student) {
	*out = *in
	if in.Phone != nil {
		in, out := &in.Phone, &out.Phone
		*out = new(Phone)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Student.
func (in *Student) DeepCopy() *Student {
	if in == nil {
		return nil
	}
	out := new(Student)
	in.DeepCopyInto(out)
	return out
}
